import React from "react";
import { NotificationCenterSubTab } from "../types";
import { SmartActionCenter } from "../../actions/SmartActionCenter";
import { useNotifications, useMarkNotificationRead, useImportJobs } from "../../../hooks/useFinanceQueries";
import { Bell, FileSpreadsheet, CheckCircle2 } from "lucide-react";

interface NotificationsTabFeedProps {
  activeSubTab: NotificationCenterSubTab;
}

const IMPORT_STATUS_STYLES: Record<string, string> = {
  COMPLETED: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20",
  FAILED: "text-rose-400 bg-rose-500/10 border-rose-500/20",
  PROCESSING: "text-indigo-400 bg-indigo-500/10 border-indigo-500/20",
  PENDING_REVIEW: "text-amber-400 bg-amber-500/10 border-amber-500/20",
};

export const NotificationsTabFeed: React.FC<NotificationsTabFeedProps> = ({ activeSubTab }) => {
  const { data: notifications = [], isLoading: notificationsLoading } = useNotifications({ limit: 20 });
  const markRead = useMarkNotificationRead();
  const { data: importJobs = [], isLoading: importsLoading } = useImportJobs({ limit: 10 });

  if (activeSubTab === "SMART_ACTIONS") {
    return <SmartActionCenter />;
  }

  if (activeSubTab === "SYSTEM_ALERTS") {
    return (
      <div className="space-y-4">
        <div className="p-6 rounded-3xl bg-slate-950/80 border border-slate-800 space-y-4 shadow-xl">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
              <Bell className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-base text-slate-100">System & Account Notifications</h3>
              <p className="text-xs text-slate-400">Alerts generated by your account activity</p>
            </div>
          </div>

          <div className="space-y-3 pt-2">
            {notificationsLoading && (
              <p className="text-xs text-slate-500">Loading notifications…</p>
            )}
            {!notificationsLoading && notifications.length === 0 && (
              <p className="text-xs text-slate-500">No notifications yet.</p>
            )}
            {notifications.map((notif) => (
              <div
                key={notif.id}
                onClick={() => !notif.isRead && markRead.mutate(notif.id)}
                className={`p-4 rounded-2xl bg-slate-900/60 border border-slate-800 flex items-start gap-3 ${!notif.isRead ? "cursor-pointer hover:border-indigo-500/40" : ""}`}
              >
                {notif.isRead ? (
                  <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
                ) : (
                  <Bell className="w-5 h-5 text-indigo-400 shrink-0 mt-0.5" />
                )}
                <div className="space-y-0.5">
                  <h4 className="text-xs font-bold text-slate-200">{notif.title}</h4>
                  <p className="text-xs text-slate-400">{notif.message}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  }

  if (activeSubTab === "ACTIVITY") {
    return (
      <div className="p-6 rounded-3xl bg-slate-950/80 border border-slate-800 space-y-4 shadow-xl">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
            <FileSpreadsheet className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-bold text-base text-slate-100">Import & Sync Activity Log</h3>
            <p className="text-xs text-slate-400">Bank statement parsing, CSV uploads & transaction sync history</p>
          </div>
        </div>

        <div className="space-y-3">
          {importsLoading && <p className="text-xs text-slate-500">Loading activity…</p>}
          {!importsLoading && importJobs.length === 0 && (
            <p className="text-xs text-slate-500">No import activity yet.</p>
          )}
          {importJobs.map((job) => (
            <div key={job.id} className="p-5 rounded-2xl bg-slate-900/60 border border-slate-800 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className={`w-2.5 h-2.5 rounded-full ${job.status === "COMPLETED" ? "bg-emerald-400" : job.status === "FAILED" ? "bg-rose-400" : "bg-indigo-400"}`} />
                <div>
                  <h4 className="text-xs font-bold text-slate-200">{job.fileName}</h4>
                  <p className="text-xs text-slate-400">
                    {job.importedRows} of {job.totalRows} transactions committed
                    {job.failedRows > 0 ? ` • ${job.failedRows} failed` : ""}
                  </p>
                </div>
              </div>
              <span className={`text-[10px] font-bold px-2.5 py-1 rounded-full border ${IMPORT_STATUS_STYLES[job.status] || "text-slate-400 bg-slate-800 border-slate-700"}`}>
                {job.status}
              </span>
            </div>
          ))}
        </div>
      </div>
    );
  }

  return null;
};
